name: ESP32 Port

on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

jobs:
  build_idf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # Setup ESP-IDF
      - name: Setup ESP-IDF
        uses: ./.github/actions/setup_esp32
        with:
          idf_ver: 5.5.1
          ccache_key: esp32_build_cmod_spiram_s2

      # Build MicroPython firmware
      - name: Build firmware
        run: tools/ci.sh esp32_build_cmod_spiram_s2

      # Upload firmware binaries as artifacts
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32_build_cmod_spiram_s2-5.5.1
          path: |
            ports/esp32/build*/firmware.bin
            ports/esp32/build*/bootloader.bin
            ports/esp32/build*/partition-table.bin
